using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoConfigGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class AutoConfigGenerator : IIncrementalGenerator
{
    public const string ATTRIBUTE = "AutoConfigGenerator.AutoConfigAttribute";

    public const string OBSERVABLE_PROPERTY_ATTRIBUTE =
        "CommunityToolkit.Mvvm.ComponentModel.ObservablePropertyAttribute";

    public const string CONFIG_PROPERTY_CHANGE_EVENT_HANDLER =
        "AutoOrganize.Library.Services.Config.ConfigPropertyChangedEventHandler";

    public const string CONFIG_PROPERTY_CHANGE_EVENT_ARGS =
        "AutoOrganize.Library.Services.Config.ConfigPropertyChangedEventArgs";

    public const string ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace AutoConfigGenerator;

        [AttributeUsage(AttributeTargets.Class, Inherited = false)]
        public class AutoConfigAttribute : Attribute
        {
            public string[] IgnoreProperties { get; }

            public AutoConfigAttribute()
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(cts => cts.AddSource("AutoConfigAttribute.g.cs", ATTRIBUTE_TEXT));

        var configClasses = context.SyntaxProvider.ForAttributeWithMetadataName(ATTRIBUTE, static (node, _) =>
                node is ClassDeclarationSyntax,
            static (syntaxContext, token) =>
            {
                if (syntaxContext.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
                {
                    return null;
                }

                if (syntaxContext.Attributes.FirstOrDefault(static x =>
                        x.AttributeClass?.ToDisplayString().Equals(ATTRIBUTE) ?? false) is not { } attribute)
                {
                    return null;
                }

                if (attribute.NamedArguments.FirstOrDefault(x => x.Key.Equals("IgnoreProperties")).Value is not
                    {
                        IsNull: false,
                    } ignorePropertiesType)
                {
                    return new ConfigClassInfo(namedTypeSymbol);
                }


                string[] ignoreProperties = ignorePropertiesType.Values.Select(x => x.Value as string)
                    .Where(x => x is not null).ToArray()!;

                return new ConfigClassInfo(namedTypeSymbol, ignoreProperties);
            }).Where(x => x is not null);

        context.RegisterSourceOutput(configClasses, ProcessClass);
    }

    private void ProcessClass(SourceProductionContext context, ConfigClassInfo? info)
    {
        if (info is null)
            return;

        var namespaceName = info.Symbol.ContainingNamespace.ToString();
        var classFullName = info.Symbol.ToString();
        var className = info.Symbol.Name;

        StringBuilder builder = new(
            $$"""
              // <auto-generated />
              #nullable enable
              namespace {{namespaceName}};

              public partial class {{className}}
              {
              """);

        builder.AppendLine();

        List<(IPropertySymbol symbol, bool hasObservable)> properties = [];

        foreach (var propertySymbol in info.Symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (propertySymbol is not
                {
                    IsReadOnly: false,
                    IsWriteOnly: false,
                    IsIndexer: false,
                    IsStatic: false,
                } || (info.IgnoreProperties?.Contains(propertySymbol.Name) ?? false)) continue;

            if (propertySymbol.GetAttributes().FirstOrDefault(x =>
                    x.AttributeClass?.ToString().Equals(OBSERVABLE_PROPERTY_ATTRIBUTE) ?? false) is null)
            {
                properties.Add((propertySymbol, false));
                continue;
            }

            properties.Add((propertySymbol, true));
        }

        foreach ((IPropertySymbol symbol, bool hasObservable) in properties)
        {
            if (!hasObservable) continue;

            builder.AppendLine($$"""
                                     public event {{CONFIG_PROPERTY_CHANGE_EVENT_HANDLER}}<{{symbol.Type}}>? {{symbol.Name}}Changed;

                                     partial void On{{symbol.Name}}Changed({{symbol.Type}} oldValue, {{symbol.Type}} newValue)
                                     {
                                         {{symbol.Name}}Changed?.Invoke(new {{CONFIG_PROPERTY_CHANGE_EVENT_ARGS}}<{{symbol.Type}}>(oldValue, newValue));
                                     }
                                 """);
            builder.AppendLine();
        }

        builder.AppendLine($$"""
                                 protected override void CopyMembers({{className}} target, {{className}} source)
                                 {
                             """);

        foreach (IPropertySymbol symbol in properties.Select(x => x.symbol))
        {
            if (symbol.Type.BaseType?.GetMembers().OfType<IMethodSymbol>() is not { } iMethodSymbols ||
                iMethodSymbols.FirstOrDefault(x => x.Name.Equals("Clone")) is not { } cloneMethodSymbol)
            {
                builder.AppendLine(
                    $$"""
                              target.{{symbol.Name}} = source.{{symbol.Name}};
                      """);
                continue;
            }

            builder.AppendLine(
                $$"""
                          target.{{symbol.Name}} = source.{{symbol.Name}}.{{cloneMethodSymbol.Name}}();
                  """);
        }


        builder.AppendLine("    }");
        builder.Append("}");

        context.AddSource($"{classFullName}.g.cs", builder.ToString());
    }


    public sealed class ConfigClassInfo
    {
        public INamedTypeSymbol Symbol { get; }
        public string[]? IgnoreProperties { get; }

        public ConfigClassInfo(INamedTypeSymbol symbol, string[]? ignoreProperties = null)
        {
            Symbol = symbol;
            IgnoreProperties = ignoreProperties;
        }
    }
}