using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AutoConfigGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class AutoConfigGenerator : IIncrementalGenerator
{
    public const string ATTRIBUTE = "AutoConfigGenerator.AutoConfigAttribute";

    public const string OBSERVABLE_PROPERTY_ATTRIBUTE =
        "CommunityToolkit.Mvvm.ComponentModel.ObservablePropertyAttribute";

    public const string CONFIG_PROPERTY_CHANGE_EVENT_HANDLER =
        "AutoOrganize.Library.Services.Config.ConfigPropertyChangedEventHandler";

    public const string CONFIG_PROPERTY_CHANGE_EVENT_ARGS =
        "AutoOrganize.Library.Services.Config.ConfigPropertyChangedEventArgs";

    public const string ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace AutoConfigGenerator;

        [AttributeUsage(AttributeTargets.Class, Inherited = false)]
        public class AutoConfigAttribute : Attribute
        {
            public string[] IgnoreProperties { get; }

            public AutoConfigAttribute()
            {
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(cts => cts.AddSource("AutoConfigAttribute.g.cs", ATTRIBUTE_TEXT));

        var configClasses = context.SyntaxProvider.ForAttributeWithMetadataName(ATTRIBUTE, static (node, _) =>
                node is ClassDeclarationSyntax,
            static (syntaxContext, token) =>
            {
                if (syntaxContext.TargetSymbol is not INamedTypeSymbol namedTypeSymbol)
                {
                    return null;
                }

                if (syntaxContext.Attributes.FirstOrDefault(static x =>
                        x.AttributeClass?.ToDisplayString().Equals(ATTRIBUTE) ?? false) is not { } attribute)
                {
                    return null;
                }

                if (attribute.NamedArguments.FirstOrDefault(x => x.Key.Equals("IgnoreProperties")).Value is not
                    {
                        IsNull: false,
                    } ignorePropertiesType)
                {
                    return new ConfigClassInfo(namedTypeSymbol);
                }


                string[] ignoreProperties = ignorePropertiesType.Values.Select(x => x.Value as string)
                    .Where(x => x is not null).ToArray()!;

                return new ConfigClassInfo(namedTypeSymbol, ignoreProperties);
            }).Where(x => x is not null);

        context.RegisterSourceOutput(configClasses, ProcessClass);
    }

    private void ProcessClass(SourceProductionContext context, ConfigClassInfo? info)
    {
        if (info is null)
            return;

        var namespaceName = info.Symbol.ContainingNamespace.ToString();
        var classFullName = info.Symbol.ToString();
        var className = info.Symbol.Name;

        StringBuilder builder = new(
            $$"""
              // <auto-generated />
              #nullable enable
              namespace {{namespaceName}};

              public partial class {{className}} : IEquatable<{{className}}>
              {
                  public CommunityToolkit.Mvvm.Messaging.WeakReferenceMessenger WeakReferenceMessenger { get; } = new();

              """);

        builder.AppendLine();

        List<(IPropertySymbol symbol, bool hasObservable)> properties = [];

        foreach (var propertySymbol in info.Symbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (propertySymbol is not
                {
                    IsReadOnly: false,
                    IsWriteOnly: false,
                    IsIndexer: false,
                    IsStatic: false,
                } || (info.IgnoreProperties?.Contains(propertySymbol.Name) ?? false)) continue;

            if (propertySymbol.GetAttributes().FirstOrDefault(x =>
                    x.AttributeClass?.ToString().Equals(OBSERVABLE_PROPERTY_ATTRIBUTE) ?? false) is null)
            {
                properties.Add((propertySymbol, false));
                continue;
            }

            properties.Add((propertySymbol, true));
        }

        foreach ((IPropertySymbol symbol, bool hasObservable) in properties)
        {
            if (!hasObservable) continue;

            builder.AppendLine($$"""
                                     public event {{CONFIG_PROPERTY_CHANGE_EVENT_HANDLER}}<{{symbol.Type}}>? {{symbol.Name}}Changed;

                                     partial void On{{symbol.Name}}Changed({{symbol.Type}} oldValue, {{symbol.Type}} newValue)
                                     {
                                         {{symbol.Name}}Changed?.Invoke(new {{CONFIG_PROPERTY_CHANGE_EVENT_ARGS}}<{{symbol.Type}}>(oldValue, newValue));
                                         CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send(WeakReferenceMessenger, new {{symbol.Name}}ChangedMessage(oldValue, newValue));
                                     }
                                 """);
            builder.AppendLine();
        }

        builder.AppendLine($$"""
                                 protected override void CopyMembers({{className}} target, {{className}} source)
                                 {
                             """);

        foreach (IPropertySymbol symbol in properties.Select(x => x.symbol))
        {
            if (!TryGetCopyMethod(symbol.Type, out var copyMethodSymbol))
            {
                builder.AppendLine(
                    $$"""
                              target.{{symbol.Name}} = source.{{symbol.Name}};
                      """);
                continue;
            }

            builder.AppendLine(
                $$"""
                          {{copyMethodSymbol.ReceiverType}}.{{copyMethodSymbol.Name}}(source.{{symbol.Name}}, target.{{symbol.Name}});
                  """);
        }


        builder.AppendLine("    }");

        if (!info.Symbol.GetMembers("Equals").OfType<IMethodSymbol>().Any(x =>
                SymbolEqualityComparer.Default.Equals(x.Parameters.FirstOrDefault()?.Type, info.Symbol)))
        {
            builder.AppendLine();
            var baseType = info.Symbol.BaseType;
            var equalsIMethodSymbols =
                baseType?.GetMembers("Equals").OfType<IMethodSymbol>()?.ToArray();
            if (baseType is not null && baseType.SpecialType is not SpecialType.System_Object &&
                equalsIMethodSymbols?.Length is > 0)
            {
                IMethodSymbol? equalsBase = equalsIMethodSymbols.FirstOrDefault(x =>
                    SymbolEqualityComparer.Default.Equals(x.Parameters.FirstOrDefault()?.Type, baseType));
                if (equalsBase is not null && equalsBase.IsVirtual)
                {
                    builder.AppendLine($$"""
                                             public override bool Equals({{baseType}}? obj)
                                             {
                                                 if(base.Equals(obj))
                                                    return true;

                                                 if(obj is not {{className}} target)
                                                     return false;

                                                 return Equals(target);
                                             }
                                         """);
                }
            }
            else
            {
                builder.AppendLine($$"""
                                         public override bool Equals(object? obj)
                                         {
                                             if(obj is not {{className}} target)
                                                return ReferenceEquals(this, obj);

                                             return Equals(target);
                                         }
                                     """);
                builder.AppendLine();
            }

            AppendClassEquals(builder, className, properties.Select(x => x.symbol), info);
        }

        if (!info.Symbol.BaseType?.GetMembers("GetHashCode").OfType<IMethodSymbol>().Any() ?? true)
        {
            builder.AppendLine();
            bool isFirst = true;
            builder.Append($$"""
                                 public override int GetHashCode()
                                 {
                                     return
                             """);

            if (info.Symbol.BaseType?.SpecialType is not SpecialType.System_Object)
            {
                builder.Append(" base.GetHashCode()");
                isFirst = false;
            }

            foreach (IPropertySymbol propertySymbol in properties.Select(x => x.symbol))
            {
                if (isFirst)
                {
                    builder.Append($" {propertySymbol.Name}.GetHashCode()");
                    continue;
                }

                builder.Append($" + {propertySymbol.Name}.GetHashCode()");
            }

            builder.AppendLine(";");
            builder.AppendLine("    }");
        }

        foreach (IPropertySymbol propertySymbol in properties.Select(x => x.symbol))
        {
            builder.AppendLine();
            builder.AppendLine($"    public sealed record {propertySymbol.Name}ChangedMessage({propertySymbol.Type} OldValue, {propertySymbol.Type} NewValue);");
        }

        builder.Append("}");
        context.AddSource($"{classFullName}.g.cs", builder.ToString());
    }

    private bool TryGetCopyMethod(ITypeSymbol typeSymbol, [NotNullWhen(true)] out IMethodSymbol? copyMethodSymbol)
    {
        ITypeSymbol? nowSymbol = typeSymbol;
        do
        {
            var methodSymbol = nowSymbol.GetMembers("Copy").OfType<IMethodSymbol>().FirstOrDefault(x => x is
                {
                    Parameters.Length: 2,
                } && SymbolEqualityComparer.Default.Equals(x.Parameters.ElementAt(0).Type, typeSymbol) && SymbolEqualityComparer.Default.Equals(x.Parameters.ElementAt(1).Type, typeSymbol)
            );
            if (methodSymbol is not null)
            {
                copyMethodSymbol = methodSymbol;
                return true;
            }

            nowSymbol = nowSymbol.BaseType;
        } while (nowSymbol is not null && nowSymbol.SpecialType is SpecialType.None);

        copyMethodSymbol = null;
        return false;
    }

    private void AppendClassEquals(StringBuilder builder, string className, IEnumerable<IPropertySymbol> properties,
        ConfigClassInfo info)
    {
        builder.AppendLine($$"""
                                 public {{(info.Symbol.IsSealed ? string.Empty : "virtual ")}}bool Equals({{className}}? obj)
                                 {
                                     if(obj is null)
                                         return false;

                                     if(ReferenceEquals(this, obj))
                                        return true;

                             """);

        foreach (IPropertySymbol symbol in properties)
        {
            builder.AppendLine(
                $$"""
                          if (!Equals({{symbol.Name}}, obj.{{symbol.Name}}))
                              return false;
                  """);

            builder.AppendLine();
        }

        builder.AppendLine("        return true;");
        builder.AppendLine("    }");
    }

    public sealed class ConfigClassInfo
    {
        public INamedTypeSymbol Symbol { get; }
        public string[]? IgnoreProperties { get; }

        public ConfigClassInfo(INamedTypeSymbol symbol, string[]? ignoreProperties = null)
        {
            Symbol = symbol;
            IgnoreProperties = ignoreProperties;
        }
    }
}