// Copyright (c) Wiesław Šoltés

//此代码修改自 https://github.com/wieslawsoltes/StaticViewLocator/blob/main/StaticViewLocator/StaticViewLocatorGenerator.cs
//在 MIT 许可证的允许下进行修改和使用
//完整的许可证 https://github.com/wieslawsoltes/StaticViewLocator?tab=MIT-1-ov-file

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace ViewModelViewModelRegistration;

[Generator(LanguageNames.CSharp)]
public class ViewModelRegistrationGenerator : IIncrementalGenerator
{
    private const string VIEW_MODEL_SUFFIX = "ViewModel";

    private const string VIEW_SUFFIX = "View";

    private const string CONFIG_ATTRIBUTE_DISPLAY_STRING =
        "ViewModelRegistrationGenerator.ViewModelConfigRegistrationAttribute";

    private const string ATTRIBUTE_DISPLAY_STRING = "ViewModelRegistrationGenerator.ViewModelRegistrationAttribute";

    private const string VIEW_MODEL_NAMESPACE_PREFIXES_PROPERTY =
        "build_property.StaticViewLocatorViewModelNamespacePrefixes";

    private const string INCLUDE_INTERNAL_VIEW_MODELS_PROPERTY =
        "build_property.StaticViewLocatorIncludeInternalViewModels";

    private const string INCLUDE_REFERENCED_ASSEMBLIES_PROPERTY =
        "build_property.StaticViewLocatorIncludeReferencedAssemblies";

    private const string ADDITIONAL_VIEW_BASE_TYPES_PROPERTY =
        "build_property.StaticViewLocatorAdditionalViewBaseTypes";

    private const string NAMESPACE_REPLACEMENT_RULES_PROPERTY =
        "build_property.StaticViewLocatorNamespaceReplacementRules";

    private const string TYPE_NAME_REPLACEMENT_RULES_PROPERTY =
        "build_property.StaticViewLocatorTypeNameReplacementRules";

    private const string STRIP_GENERIC_ARITY_FROM_VIEW_NAME_PROPERTY =
        "build_property.StaticViewLocatorStripGenericArityFromViewName";

    private const string INTERFACE_PREFIXES_TO_STRIP_PROPERTY =
        "build_property.StaticViewLocatorInterfacePrefixesToStrip";

    private const string ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        [global::System.AttributeUsageAttribute(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        public sealed class ViewModelRegistrationAttribute : Attribute
        {
            public ViewModelLifetime Lifetime { get; }

            public ViewModelRegistrationAttribute(ViewModelLifetime lifetime = ViewModelLifetime.Transient)
            {
                Lifetime = lifetime;
            }
        }
        """;

    private const string CONFIG_ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        [global::System.AttributeUsageAttribute(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class ViewModelConfigRegistrationAttribute : Attribute
        {
            public Type ConfigType { get; }

            public ViewModelConfigRegistrationAttribute(Type configType)
            {
                ConfigType = configType;
            }
        }
        """;

    private const string ENUM_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        public enum ViewModelLifetime
        {
            None,
            Transient,
            Singleton,
            Scoped
        }
        """;

    private readonly struct GeneratorOptions
    {
        public GeneratorOptions(
            ImmutableArray<string> namespacePrefixes,
            bool includeInternalViewModels,
            bool includeReferencedAssemblies,
            ImmutableArray<string> additionalViewBaseTypes,
            ImmutableArray<ReplacementRule> namespaceReplacementRules,
            ImmutableArray<ReplacementRule> typeNameReplacementRules,
            bool stripGenericArityFromViewName,
            ImmutableArray<string> interfacePrefixesToStrip)
        {
            NamespacePrefixes = namespacePrefixes;
            IncludeInternalViewModels = includeInternalViewModels;
            IncludeReferencedAssemblies = includeReferencedAssemblies;
            AdditionalViewBaseTypes = additionalViewBaseTypes;
            NamespaceReplacementRules = namespaceReplacementRules;
            TypeNameReplacementRules = typeNameReplacementRules;
            StripGenericArityFromViewName = stripGenericArityFromViewName;
            InterfacePrefixesToStrip = interfacePrefixesToStrip;
        }

        public ImmutableArray<string> NamespacePrefixes { get; }
        public bool IncludeInternalViewModels { get; }
        public bool IncludeReferencedAssemblies { get; }
        public ImmutableArray<string> AdditionalViewBaseTypes { get; }
        public ImmutableArray<ReplacementRule> NamespaceReplacementRules { get; }
        public ImmutableArray<ReplacementRule> TypeNameReplacementRules { get; }
        public bool StripGenericArityFromViewName { get; }
        public ImmutableArray<string> InterfacePrefixesToStrip { get; }
    }

    private readonly struct ReplacementRule
    {
        public ReplacementRule(string from, string to)
        {
            From = from;
            To = to;
        }

        public string From { get; }
        public string To { get; }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ViewModelRegistrationAttribute.g.cs", SourceText.From(ATTRIBUTE_TEXT, Encoding.UTF8)));

        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ViewModelLifetime.g.cs", SourceText.From(ENUM_TEXT, Encoding.UTF8)));

        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("ViewModelConfigRegistrationAttribute.g.cs",
                SourceText.From(CONFIG_ATTRIBUTE_TEXT, Encoding.UTF8)));

        var viewModelsProvider = context.SyntaxProvider
            .ForAttributeWithMetadataName(ATTRIBUTE_DISPLAY_STRING,
                static (node, _) =>
                    node is TypeDeclarationSyntax typeDeclaration
                        and (ClassDeclarationSyntax or InterfaceDeclarationSyntax) &&
                    typeDeclaration.Identifier.ValueText.EndsWith(VIEW_MODEL_SUFFIX, StringComparison.Ordinal),
                static (generatorContext, _) =>
                    generatorContext.TargetSymbol as INamedTypeSymbol)
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        var optionsProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => GetGeneratorOptions(options));

        var referencedViewModelsProvider = context.CompilationProvider
            .Combine(optionsProvider)
            .Select(static (pair, _) =>
                pair.Right.IncludeReferencedAssemblies
                    ? GetReferencedViewModels(pair.Left)
                    : ImmutableArray<INamedTypeSymbol>.Empty);

        var allViewModelsProvider = viewModelsProvider
            .Combine(referencedViewModelsProvider)
            .Select(static (pair, _) => pair.Left.AddRange(pair.Right));


        var inputs = context.CompilationProvider
            .Combine(allViewModelsProvider)
            .Combine(optionsProvider);

        context.RegisterSourceOutput(inputs, static (sourceProductionContext, tuple) =>
        {
            var ((compilation, viewModelSymbols), options) = tuple;

            var classSource = ProcessClass(compilation, viewModelSymbols, options);
            sourceProductionContext.AddSource(
                $"ServiceCollectionExtension.g.cs",
                SourceText.From(classSource, Encoding.UTF8));
        });
    }

    private static ImmutableArray<INamedTypeSymbol> GetReferencedViewModels(Compilation compilation)
    {
        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            CollectViewModels(assembly.GlobalNamespace, builder);
        }

        return builder.ToImmutable();
    }

    private static void CollectViewModels(INamespaceSymbol namespaceSymbol,
        ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            CollectViewModels(type, builder);
        }

        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            CollectViewModels(child, builder);
        }
    }

    private static void CollectViewModels(INamedTypeSymbol typeSymbol, ImmutableArray<INamedTypeSymbol>.Builder builder)
    {
        if (IsViewModelType(typeSymbol))
        {
            builder.Add(typeSymbol);
        }

        foreach (var nested in typeSymbol.GetTypeMembers())
        {
            CollectViewModels(nested, builder);
        }
    }

    private static GeneratorOptions GetGeneratorOptions(AnalyzerConfigOptionsProvider optionsProvider)
    {
        var namespacePrefixes = GetNamespacePrefixes(optionsProvider);
        var includeInternal = GetIncludeInternalViewModels(optionsProvider);
        var includeReferencedAssemblies = GetIncludeReferencedAssemblies(optionsProvider);
        var additionalViewBaseTypes = GetAdditionalViewBaseTypes(optionsProvider);
        var namespaceReplacementRules = GetReplacementRules(optionsProvider, NAMESPACE_REPLACEMENT_RULES_PROPERTY,
            new ReplacementRule("ViewModels", "Views"));
        var typeNameReplacementRules = GetReplacementRules(optionsProvider, TYPE_NAME_REPLACEMENT_RULES_PROPERTY,
            new ReplacementRule(VIEW_MODEL_SUFFIX, VIEW_SUFFIX));
        var stripGenericArityFromViewName = GetStripGenericArityFromViewName(optionsProvider);
        var interfacePrefixesToStrip = GetInterfacePrefixesToStrip(optionsProvider);

        return new GeneratorOptions(
            namespacePrefixes,
            includeInternal,
            includeReferencedAssemblies,
            additionalViewBaseTypes,
            namespaceReplacementRules,
            typeNameReplacementRules,
            stripGenericArityFromViewName,
            interfacePrefixesToStrip);
    }

    private static ImmutableArray<string> GetNamespacePrefixes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(VIEW_MODEL_NAMESPACE_PREFIXES_PROPERTY, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split([';', ','], StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static bool GetIncludeInternalViewModels(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(INCLUDE_INTERNAL_VIEW_MODELS_PROPERTY, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeInternal) && includeInternal;
    }

    private static bool GetIncludeReferencedAssemblies(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(INCLUDE_REFERENCED_ASSEMBLIES_PROPERTY, out var rawValue))
        {
            return false;
        }

        return bool.TryParse(rawValue, out var includeReferencedAssemblies) && includeReferencedAssemblies;
    }

    private static ImmutableArray<string> GetAdditionalViewBaseTypes(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(ADDITIONAL_VIEW_BASE_TYPES_PROPERTY, out var rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        if (string.IsNullOrWhiteSpace(rawValue))
        {
            return ImmutableArray<string>.Empty;
        }

        var parts = rawValue.Split([';', ','], StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.ToImmutable();
    }

    private static ImmutableArray<ReplacementRule> GetReplacementRules(
        AnalyzerConfigOptionsProvider optionsProvider,
        string propertyName,
        params ReplacementRule[] defaults)
    {
        var builder = ImmutableArray.CreateBuilder<ReplacementRule>();

        if (!optionsProvider.GlobalOptions.TryGetValue(propertyName, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            foreach (var replacementRule in defaults)
            {
                builder.Add(replacementRule);
            }

            return builder.ToImmutable();
        }

        var parts = rawValue.Split([';', ','], StringSplitOptions.RemoveEmptyEntries);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length == 0)
            {
                continue;
            }

            var separatorIndex = trimmed.IndexOf('=');
            if (separatorIndex <= 0 || separatorIndex == trimmed.Length - 1)
            {
                continue;
            }

            var from = trimmed.Substring(0, separatorIndex).Trim();
            var to = trimmed.Substring(separatorIndex + 1).Trim();

            if (from.Length == 0)
            {
                continue;
            }

            builder.Add(new ReplacementRule(from, to));
        }

        foreach (var replacementRule in defaults)
        {
            builder.Add(replacementRule);
        }

        return builder.ToImmutable();
    }

    private static bool GetStripGenericArityFromViewName(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(STRIP_GENERIC_ARITY_FROM_VIEW_NAME_PROPERTY, out var rawValue))
        {
            return true;
        }

        return !bool.TryParse(rawValue, out var stripGenericArityFromViewName) || stripGenericArityFromViewName;
    }

    private static ImmutableArray<string> GetInterfacePrefixesToStrip(AnalyzerConfigOptionsProvider optionsProvider)
    {
        if (!optionsProvider.GlobalOptions.TryGetValue(INTERFACE_PREFIXES_TO_STRIP_PROPERTY, out var rawValue) ||
            string.IsNullOrWhiteSpace(rawValue))
        {
            return ["I"];
        }

        var parts = rawValue.Split([';', ','], StringSplitOptions.RemoveEmptyEntries);
        var builder = ImmutableArray.CreateBuilder<string>(parts.Length);
        foreach (var part in parts)
        {
            var trimmed = part.Trim();
            if (trimmed.Length > 0)
            {
                builder.Add(trimmed);
            }
        }

        return builder.Count == 0 ? ["I"] : builder.ToImmutable();
    }

    private static bool IsViewModelType(INamedTypeSymbol symbol)
    {
        if (symbol.TypeKind != TypeKind.Class && symbol.TypeKind != TypeKind.Interface)
        {
            return false;
        }

        return symbol.Name.EndsWith(VIEW_MODEL_SUFFIX, StringComparison.Ordinal);
    }

    private static bool IsViewModelCandidate(INamedTypeSymbol symbol, Compilation compilation, GeneratorOptions options)
    {
        if (!IsViewModelType(symbol))
        {
            return false;
        }

        if (!IsViewModelAccessible(symbol, compilation, options.IncludeInternalViewModels))
        {
            return false;
        }

        if (options.NamespacePrefixes.IsDefaultOrEmpty)
        {
            return true;
        }

        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        if (namespaceName.Length == 0)
        {
            return false;
        }

        return MatchesNamespace(namespaceName, options.NamespacePrefixes);
    }

    private static bool IsViewModelAccessible(
        INamedTypeSymbol symbol,
        Compilation compilation,
        bool includeInternal)
    {
        if (SymbolEqualityComparer.Default.Equals(symbol.ContainingAssembly, compilation.Assembly))
        {
            return true;
        }

        if (symbol.DeclaredAccessibility == Accessibility.Public && IsContainingTypesPublic(symbol))
        {
            return true;
        }

        if (!includeInternal || symbol.DeclaredAccessibility != Accessibility.Internal)
        {
            return false;
        }

        if (!IsContainingTypesAtMostInternal(symbol))
        {
            return false;
        }

        return symbol.ContainingAssembly.GivesAccessTo(compilation.Assembly);
    }

    private static bool IsContainingTypesPublic(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            if (containing.DeclaredAccessibility != Accessibility.Public)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsContainingTypesAtMostInternal(INamedTypeSymbol symbol)
    {
        for (var containing = symbol.ContainingType; containing is not null; containing = containing.ContainingType)
        {
            var accessibility = containing.DeclaredAccessibility;
            if (accessibility != Accessibility.Public && accessibility != Accessibility.Internal)
            {
                return false;
            }
        }

        return true;
    }

    private static bool MatchesNamespace(string namespaceName, ImmutableArray<string> namespacePrefixes)
    {
        foreach (var prefix in namespacePrefixes)
        {
            if (string.IsNullOrWhiteSpace(prefix))
            {
                continue;
            }

            var normalized = prefix.Trim();
            if (namespaceName.Equals(normalized, StringComparison.Ordinal) ||
                namespaceName.StartsWith(normalized + ".", StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static string ApplyReplacementRules(string input, ImmutableArray<ReplacementRule> replacementRules)
    {
        var value = input;

        foreach (var replacementRule in replacementRules)
        {
            value = value.Replace(replacementRule.From, replacementRule.To);
        }

        return value;
    }

    private static string GetMetadataTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.MetadataName);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeName(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.Name);
        }

        return string.Join(".", parts);
    }

    private static string GetSourceTypeReference(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            var part = current.Name;
            if (current.IsGenericType)
            {
                part += "<" + new string(',', current.TypeParameters.Length - 1) + ">";
            }

            parts.Push(part);
        }

        var typeName = string.Join(".", parts);
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        return string.IsNullOrEmpty(namespaceName) ? typeName : $"{namespaceName}.{typeName}";
    }

    private static string StripGenericArity(string typeName)
    {
        var parts = typeName.Split('.');

        for (var i = 0; i < parts.Length; i++)
        {
            var tickIndex = parts[i].IndexOf('`');
            if (tickIndex >= 0)
            {
                parts[i] = parts[i].Substring(0, tickIndex);
            }
        }

        return string.Join(".", parts);
    }

    private static string StripInterfacePrefix(string typeName, ImmutableArray<string> interfacePrefixesToStrip)
    {
        foreach (var prefix in interfacePrefixesToStrip)
        {
            if (string.IsNullOrEmpty(prefix))
            {
                continue;
            }

            var parts = typeName.Split('.');
            var last = parts[^1];
            if (!last.StartsWith(prefix, StringComparison.Ordinal) || last.Length <= prefix.Length)
            {
                continue;
            }

            parts[^1] = last[prefix.Length..];
            return string.Join(".", parts);
        }

        return typeName;
    }

    private static string ProcessClass(
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> viewModelSymbols,
        GeneratorOptions options)
    {
        var relevantViewModels = new List<INamedTypeSymbol>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var symbol in viewModelSymbols)
        {
            if (!IsViewModelCandidate(symbol, compilation, options))
            {
                continue;
            }

            if (seen.Add(symbol))
            {
                relevantViewModels.Add(symbol);
            }
        }

        relevantViewModels.Sort(static (left, right) =>
            string.Compare(left.ToDisplayString(), right.ToDisplayString(), StringComparison.Ordinal));

        var source = new StringBuilder(
            $$"""
              // <auto-generated />
              #nullable enable
              using System;
              using System.Collections.Generic;
              using System.Diagnostics.CodeAnalysis;
              using Microsoft.Extensions.DependencyInjection;
              using Avalonia.Controls;

              namespace ViewModelRegistrationGenerator;

              public static class ServiceCollectionExtension
              {
              """);

        source.AppendLine();

        source.AppendLine("    public static IServiceCollection AddViewModels(this IServiceCollection services)");
        source.AppendLine("    {");

        var viewBaseTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var userControlViewSymbol = compilation.GetTypeByMetadataName("Avalonia.Controls.UserControl");
        if (userControlViewSymbol is not null)
        {
            viewBaseTypes.Add(userControlViewSymbol);
        }

        var windowViewSymbol = compilation.GetTypeByMetadataName("Avalonia.Controls.Window");
        if (windowViewSymbol is not null)
        {
            viewBaseTypes.Add(windowViewSymbol);
        }

        foreach (var additionalTypeName in options.AdditionalViewBaseTypes)
        {
            var additionalSymbol = compilation.GetTypeByMetadataName(additionalTypeName);
            if (additionalSymbol is not null)
            {
                viewBaseTypes.Add(additionalSymbol);
            }
        }

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var namespaceNameViewModel = viewModelSymbol.ContainingNamespace.ToDisplayString();
            var sourceTypeNameViewModel = GetSourceTypeName(viewModelSymbol);
            var metadataTypeNameViewModel = GetMetadataTypeName(viewModelSymbol);

            var sourceNamespaceView = ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);
            var metadataNamespaceView =
                ApplyReplacementRules(namespaceNameViewModel, options.NamespaceReplacementRules);

            var sourceTypeNameView = ApplyReplacementRules(sourceTypeNameViewModel, options.TypeNameReplacementRules);
            var metadataTypeNameView =
                ApplyReplacementRules(metadataTypeNameViewModel, options.TypeNameReplacementRules);

            if (viewModelSymbol.TypeKind == TypeKind.Interface)
            {
                sourceTypeNameView = StripInterfacePrefix(sourceTypeNameView, options.InterfacePrefixesToStrip);
                metadataTypeNameView = StripInterfacePrefix(metadataTypeNameView, options.InterfacePrefixesToStrip);
            }

            if (options.StripGenericArityFromViewName)
            {
                sourceTypeNameView = StripGenericArity(sourceTypeNameView);
                metadataTypeNameView = StripGenericArity(metadataTypeNameView);
            }

            var classNameViewModel = GetSourceTypeReference(viewModelSymbol);
            var classNameView = $"{sourceNamespaceView}.{sourceTypeNameView}";
            var metadataNameView = $"{metadataNamespaceView}.{metadataTypeNameView}";

            var viewSymbol = compilation.GetTypeByMetadataName(metadataNameView);

            var isSupportedView = false;
            if (viewSymbol is not null && viewBaseTypes.Count > 0)
            {
                for (var current = viewSymbol; current is not null; current = current.BaseType)
                {
                    if (viewBaseTypes.Contains(current))
                    {
                        isSupportedView = true;
                        break;
                    }
                }
            }

            if (viewSymbol is null || viewSymbol.IsGenericType)
            {
                isSupportedView = false;
            }

            var lifetimeString = GetLifetimeString(viewModelSymbol);

            if (lifetimeString is null)
            {
                continue;
            }

            if (isSupportedView)
            {
                source.AppendLine($$"""
                                            services.Add{{lifetimeString}}<{{classNameViewModel}}>();
                                            services.Add{{lifetimeString}}<{{classNameView}}>();
                                    """);
            }
            else
            {
                source.AppendLine($$"""
                                            services.Add{{lifetimeString}}<{{classNameViewModel}}>();
                                            // services.Add{{lifetimeString}}<{{classNameView}}>();
                                    """);
            }

            IfHasAddConfigRegistration(viewModelSymbol, source);
            source.AppendLine();
        }


        source.AppendLine("        return services;");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string? GetLifetimeString(ITypeSymbol typeSymbol)
    {
        var data = typeSymbol.GetAttributes().FirstOrDefault(x =>
            x.AttributeClass?.ToDisplayString().Equals(ATTRIBUTE_DISPLAY_STRING) ?? false);
        var lifetimeTyped = data?.ConstructorArguments.Length > 0 ? data.ConstructorArguments[0] : default;

        if (lifetimeTyped.IsNull || lifetimeTyped.Value is not int i)
            return null;

        return i switch
        {
            0 => null,
            1 => "Transient",
            2 => "Singleton",
            3 => "Scoped",
            _ => null
        };
    }

    private static void IfHasAddConfigRegistration(ITypeSymbol typeSymbol, StringBuilder builder)
    {
        foreach (AttributeData attributeData in typeSymbol.GetAttributes().Where(x =>
                     x.AttributeClass?.ToDisplayString().Equals(CONFIG_ATTRIBUTE_DISPLAY_STRING) ?? false))
        {
            if (attributeData.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                continue;

            builder.AppendLine($"""
                                        services.AddTransient<{type.ToDisplayString()}>((serviceProvider) => serviceProvider.GetRequiredService<AutoOrganize.Library.Services.Config.IFileConfigManager>().GetConfigOrLoad<{type.ToDisplayString()}>());
                                """);
        }
    }
}