// Copyright (c) Wiesław Šoltés

//此代码修改自 https://github.com/wieslawsoltes/StaticViewLocator/blob/main/StaticViewLocator/StaticViewLocatorGenerator.cs
//在 MIT 许可证的允许下进行修改和使用
//完整的许可证 https://github.com/wieslawsoltes/StaticViewLocator?tab=MIT-1-ov-file

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ViewModelViewModelRegistration;

[Generator(LanguageNames.CSharp)]
public class ViewModelRegistrationGenerator : IIncrementalGenerator
{
    private const string ATTRIBUTE_DISPLAY_STRING = "ViewModelRegistrationGenerator.ViewModelRegistrationAttribute";

    private const string CONFIG_ATTRIBUTE_DISPLAY_STRING =
        "ViewModelRegistrationGenerator.ViewModelConfigRegistrationAttribute";

    private const string WINDOW_MODEL_SUFFIX = "WindowViewModel";
    private const string WINDOW_SUFFIX = "Window";
    private const string VIEW_MODEL_SUFFIX = "ViewModel";
    private const string VIEW_SUFFIX = "View";

    private const string ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        [global::System.AttributeUsageAttribute(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        public sealed class ViewModelRegistrationAttribute : Attribute
        {
            public ViewModelLifetime Lifetime { get; }

            public ViewModelRegistrationAttribute(ViewModelLifetime lifetime = ViewModelLifetime.Transient)
            {
                Lifetime = lifetime;
            }
        }
        """;

    private const string CONFIG_ATTRIBUTE_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        [global::System.AttributeUsageAttribute(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class ViewModelConfigRegistrationAttribute : Attribute
        {
            public Type ConfigType { get; }

            public ViewModelConfigRegistrationAttribute(Type configType)
            {
                ConfigType = configType;
            }
        }
        """;

    private const string ENUM_TEXT =
        """
        // <auto-generated />
        using System;

        namespace ViewModelRegistrationGenerator;

        public enum ViewModelLifetime
        {
            None,
            Transient,
            Singleton,
            Scoped
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static igpc =>
            igpc.AddSource("ViewModelRegistrationAttribute.g.cs", ATTRIBUTE_TEXT));

        context.RegisterPostInitializationOutput(static igpc =>
            igpc.AddSource("ViewModelConfigRegistrationAttribute.g.cs", CONFIG_ATTRIBUTE_TEXT));

        context.RegisterPostInitializationOutput(static igpc =>
            igpc.AddSource("ViewModelLifetime.g.cs", ENUM_TEXT));

        var viewModelsProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax classDeclaration &&
                                    classDeclaration.Identifier.ValueText.EndsWith(VIEW_MODEL_SUFFIX,
                                        StringComparison.Ordinal)
                ,
                static (generatorContext, cancellationToken) =>
                {
                    var classDeclaration = (ClassDeclarationSyntax)generatorContext.Node;
                    if (generatorContext.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken) is not
                        { } symbol)
                    {
                        return null;
                    }

                    return symbol.IsAbstract ? null : symbol;
                })
            .Where(static symbol => symbol is not null)
            .Select(static (symbol, _) => symbol!)
            .Collect();

        var inputs = context.CompilationProvider
            .Combine(viewModelsProvider);

        context.RegisterSourceOutput(inputs, static (sourceProductionContext, tuple) =>
        {
            (Compilation compilation, ImmutableArray<INamedTypeSymbol> viewModelSymbols) = tuple;
            if (viewModelSymbols.Length == 0) return;
            AddClass(sourceProductionContext, compilation, viewModelSymbols);
        });
    }

    private static void AddClass(SourceProductionContext context, Compilation compilation,
        ImmutableArray<INamedTypeSymbol> viewModelSymbols)
    {
        var relevantViewModels = new List<INamedTypeSymbol>();
        var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var symbol in viewModelSymbols)
        {
            if (!symbol.Name.EndsWith(VIEW_MODEL_SUFFIX, StringComparison.Ordinal) || symbol.IsAbstract)
            {
                continue;
            }

            if (seen.Add(symbol))
            {
                relevantViewModels.Add(symbol);
            }
        }

        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters |
                             SymbolDisplayGenericsOptions.IncludeTypeConstraints |
                             SymbolDisplayGenericsOptions.IncludeVariance);

        relevantViewModels.Sort(static (left, right) =>
            string.Compare(left.ToDisplayString(), right.ToDisplayString(), StringComparison.Ordinal));

        var source = new StringBuilder(
            $$"""
              // <auto-generated />
              #nullable enable
              using System;
              using System.Collections.Generic;
              using Microsoft.Extensions.DependencyInjection;
              using Avalonia.Controls;

              namespace ViewModelRegistrationGenerator;

              public static class ServiceCollectionExtension
              {
              """);

        source.AppendLine();
        source.AppendLine("    public static IServiceCollection AddViewModels(this IServiceCollection services)");
        source.AppendLine("    {");
        var controlViewSymbol = compilation.GetTypeByMetadataName("Avalonia.Controls.Control")!;

        foreach (var viewModelSymbol in relevantViewModels)
        {
            var classNameViewModel =
                $"{viewModelSymbol.ContainingNamespace.ToDisplayString()}.{viewModelSymbol.ToDisplayString(format)}";
            var classNameView = classNameViewModel
                .Replace(WINDOW_MODEL_SUFFIX, WINDOW_SUFFIX)
                .Replace(VIEW_MODEL_SUFFIX, VIEW_SUFFIX);
            var viewSymbol = compilation.GetTypeByMetadataName(classNameView);

            if (viewSymbol is null)
            {
                classNameView = classNameViewModel.Replace(VIEW_MODEL_SUFFIX, VIEW_SUFFIX);
                viewSymbol = compilation.GetTypeByMetadataName(classNameView);
            }

            if (viewSymbol is null || !InheritsFrom(viewSymbol, controlViewSymbol))
            {
                source.AppendLine(
                    $"    // No registration for {classNameViewModel} because view not found: {classNameView}");
            }
            else
            {
                string? lifetimeString = GetLifetimeString(viewModelSymbol);
                if (lifetimeString is null)
                {
                    source.AppendLine($$"""
                                                //ignore {{classNameViewModel}} and {{classNameView}}
                                        """);
                }
                else
                {
                    source.AppendLine($$"""
                                                services.Add{{lifetimeString}}<{{classNameViewModel}}>();
                                                services.Add{{lifetimeString}}<{{classNameView}}>();
                                        """);
                }

                IfHasAddConfigRegistration(viewModelSymbol, source);
            }

            source.AppendLine();
        }

        source.AppendLine("\t\treturn services;");
        source.AppendLine("\t}");
        source.AppendLine("}");
        context.AddSource(
            "ServiceCollectionExtension.g.cs", source.ToString());
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol controlSymbol)
    {
        var current = symbol;
        while (current != null)
        {
            if (current.Equals(controlSymbol, SymbolEqualityComparer.Default))
                return true;
            current = current.BaseType;
        }

        return false;
    }

    private static string? GetLifetimeString(ITypeSymbol typeSymbol, string defaultValue = "Transient")
    {
        var data = typeSymbol.GetAttributes().FirstOrDefault(x =>
            x.AttributeClass?.ToDisplayString().Equals(ATTRIBUTE_DISPLAY_STRING) ?? false);
        var lifetimeTyped = data?.ConstructorArguments.Length > 0 ? data.ConstructorArguments[0] : default;

        if (lifetimeTyped.IsNull)
            return defaultValue;

        if (lifetimeTyped.Value is not int i)
            return defaultValue;

        return i switch
        {
            0 => null,
            1 => "Transient",
            2 => "Singleton",
            3 => "Scoped",
            _ => defaultValue
        };
    }

    private static void IfHasAddConfigRegistration(ITypeSymbol typeSymbol, StringBuilder builder)
    {
        foreach (AttributeData attributeData in typeSymbol.GetAttributes().Where(x =>
                     x.AttributeClass?.ToDisplayString().Equals(CONFIG_ATTRIBUTE_DISPLAY_STRING) ?? false))
        {
            if (attributeData.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                continue;

            builder.AppendLine($"""
                                        services.AddTransient<{type.ToDisplayString()}>((serviceProvider) => serviceProvider.GetRequiredService<AutoOrganize.Library.Services.Config.IFileConfigManager>().GetConfigOrLoad<{type.ToDisplayString()}>());
                                """);
        }
    }
}